run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - gofmt
    - goimports
    - gocyclo
    - golint
  disable:
    - maligned

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
